# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eeg_link.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'eeg_link.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65\x65g_link.proto\x12\x03\x65\x65g\"m\n\x08\x45\x65gFrame\x12\x0b\n\x03seq\x18\x01 \x01(\x03\x12\x11\n\tt_sent_ms\x18\x02 \x01(\x01\x12\x0c\n\x04rate\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x12\x13\n\x0btrue_action\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x06 \x03(\x02\"6\n\nControlAck\x12\x12\n\naction_seq\x18\x01 \x01(\x03\x12\x14\n\x0ct_control_ms\x18\x02 \x01(\x01\"T\n\rClientMessage\x12\x1c\n\x03\x65\x65g\x18\x01 \x01(\x0b\x32\r.eeg.EegFrameH\x00\x12\x1e\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\x0f.eeg.ControlAckH\x00\x42\x05\n\x03msg\"\x9b\x01\n\x0c\x41\x63tionResult\x12\x12\n\naction_seq\x18\x01 \x01(\x03\x12\x0f\n\x07\x65\x65g_seq\x18\x02 \x01(\x03\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x12\n\nt_infer_ms\x18\x05 \x01(\x01\x12\x18\n\x10\x61\x63\x63uracy_percent\x18\x06 \x01(\x02\x12\x14\n\x0c\x61\x63tion_probs\x18\x07 \x03(\x02\";\n\rServerMessage\x12#\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x11.eeg.ActionResultH\x00\x42\x05\n\x03msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eeg_link_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EEGFRAME']._serialized_start=23
  _globals['_EEGFRAME']._serialized_end=132
  _globals['_CONTROLACK']._serialized_start=134
  _globals['_CONTROLACK']._serialized_end=188
  _globals['_CLIENTMESSAGE']._serialized_start=190
  _globals['_CLIENTMESSAGE']._serialized_end=274
  _globals['_ACTIONRESULT']._serialized_start=277
  _globals['_ACTIONRESULT']._serialized_end=432
  _globals['_SERVERMESSAGE']._serialized_start=434
  _globals['_SERVERMESSAGE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
